// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVmN4INHRPs1-0xAH0H40X-Ehf0pWoMb0',
    appId: '1:641197906136:web:618743992e19597a0d5fad',
    messagingSenderId: '641197906136',
    projectId: 'case-flutter',
    authDomain: 'case-flutter.firebaseapp.com',
    storageBucket: 'case-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiz1PNuF0-Pc_BHMIE9QL83jippWwyun4',
    appId: '1:641197906136:android:41dd6042d7f654f00d5fad',
    messagingSenderId: '641197906136',
    projectId: 'case-flutter',
    storageBucket: 'case-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWtDyxOji8y3BZC02TMH4Na8T5amu0U3k',
    appId: '1:641197906136:ios:788da69022dc9c9a0d5fad',
    messagingSenderId: '641197906136',
    projectId: 'case-flutter',
    storageBucket: 'case-flutter.appspot.com',
    iosClientId: '641197906136-ifnn8p82mluvkpd0u02deod933d6vqg9.apps.googleusercontent.com',
    iosBundleId: 'com.example.turkTicaretCaseApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWtDyxOji8y3BZC02TMH4Na8T5amu0U3k',
    appId: '1:641197906136:ios:788da69022dc9c9a0d5fad',
    messagingSenderId: '641197906136',
    projectId: 'case-flutter',
    storageBucket: 'case-flutter.appspot.com',
    iosClientId: '641197906136-ifnn8p82mluvkpd0u02deod933d6vqg9.apps.googleusercontent.com',
    iosBundleId: 'com.example.turkTicaretCaseApplication',
  );
}
